
% design variables
x = struct('capture_width', 10,...
    'wec_type', 'point_absorber',...
    'pen_diameter', 1,...
    'pen_height', 0.5);

% parameters
wec_types = {'attenuator','terminator','point_absorber'};
capture_width_ratios = [0.5, 0.5, 0.5];
wave_dampings = [0.5, 0.5, 0.5];

env_params = struct('O2_in', 1,...
            'O2_min', 1,...
            'P_f', 1,...
            'P_p', 1,...
            'U_min', 1,...
            'tau', 1,...
            'permeability', 1,...
            'F_f', 1,...
            'F_p', 1,...
            'F_c', 1,...
            'A_f', 1,...
            'A_p', 1,...
            'A_c', 1,...
            'O_f', 1,...
            'O_p', 1,...
            'O_c', 1,...
            'C_f', 1,...
            'C_p', 1,...
            'C_c', 1);

p = struct('wave_height', 2,...
    'wave_period', 5,...
    'wave_damping_dict', cell2struct(num2cell(wave_dampings), wec_types,2),...
    'capture_width_ratio_dict', cell2struct(num2cell(capture_width_ratios),wec_types,2),...
    'wec_unit_cost', 1000,...
    'pen_unit_cost', 1000,...
    'env_params',env_params,...
    'loss_rate', 0.15,...
    'num_pens', 8,...
    'spacing', 10,...
    'harvest_weight', 1,...
    'stocking_density', 1);

% simulation
[J, g, h] = simulate(x,p);
